### ISSUE TITLE
Support Monterey

### ISSUE THREAD

**Issue by ByteHolic** [aditnanda/Lenovo-G40-70-OpenCore_0.6.3-BigSur_11.0.1#3]
Please update file for use macos monterey

**Comment by mrbongo1981** [comment]
ya stuck pal try mine then everything is working fine ...updated to 0.79 
https://github.com/mrbongo1981/Monterey-EFI-Lenovo-G50-80

**Comment by ByteHolic** [comment]
Thanks ❤️

**Comment by ByteHolic** [comment]
.
